### PR TITLE
Update to Ruby 2.5 and Upgrade Dependencies

### PR DESCRIPTION
**Pull request by nllong**

### CODE REVIEW

**Comment by nllong** [comment]
@kflemin -- can you verify that the upload of components works? 

The unit tests are failing and I'm concerned that there may be a bigger issue. Note that they were failing before this upgrade.
```
rspec ./spec/api/api_components_spec.rb:147 # BCL API ::Component when logged in post component should be able to post new component with no ids set
rspec ./spec/api/api_components_spec.rb:156 # BCL API ::Component when logged in post component should fail when posting a component with a non-unique uuid
rspec ./spec/api/api_components_spec.rb:164 # BCL API ::Component when logged in post component should update the component if the uuid already exists
rspec ./spec/api/api_components_spec.rb:179 # BCL API ::Component when logged in post component should fail when posting component with same uuid/vid components
rspec ./spec/api/api_components_spec.rb:189 # BCL API ::Component when logged in posting multiple components should push 2 components
rspec ./spec/api/api_components_spec.rb:196 # BCL API ::Component when logged in posting multiple components should post 0 components when checking receipt files
rspec ./spec/api/api_measures_spec.rb:27 # BCL API ::Measure and uploading measures should upload a measure
rspec ./spec/api/api_measures_spec.rb:35 # BCL API ::Measure and uploading measures should update a measure
rspec ./spec/api/api_measures_spec.rb:41 # BCL API ::Measure and uploading measures should fail upload of existing measure (UUID match)
rspec ./spec/api/api_measures_spec.rb:48 # BCL API ::Measure and uploading measures should fail update of existing measure with same Version ID (VUUID match)
rspec ./spec/api/api_measures_spec.rb:60 # BCL API ::Measure and uploading measures should fail upload/update with topLevel directory in tar.gz
rspec ./spec/api/api_measures_spec.rb:67 # BCL API ::Measure and uploading measures should fail upload/update with bad attribute in xml
rspec ./spec/api/api_measures_spec.rb:74 # BCL API ::Measure and uploading measures should fail upload/update when there is an <error> tag in the xml
rspec ./spec/api/api_measures_spec.rb:81 # BCL API ::Measure and uploading measures should fail upload/update when file described in xml is not in tar.gz
``

**Comment by kflemin** [comment]
@nllong everything was passing for me except for 2 component tests:
rspec ./spec/api/api_components_spec.rb:147
rspec ./spec/api/api_components_spec.rb:164

I made a fix on BCL dev that resolved both issues.  Can you confirm that this is working for you as well (on dev)?

**Comment by nllong** [comment]
Okay, this worked after deleting the test measure. Thanks for the help. Can you approve this PR, then I'll merge and release it?

**Comment by kflemin** [comment]
approved!

**Pull request merged**
