### PR TITLE
 Remove hard dependency on ruby 2.7 as we prepare for ruby 3.2.2

### PR DESCRIPTION
**Pull request by jmarrec**

### CODE REVIEW

**Comment by kbenne** [comment]
@DavidGoldwasser @kflemin I think one of you need to merge this. I do not have permission.

**Review by DavidGoldwasser — APPROVED** [review]

**Comment by kbenne** [comment]
@kflemin I think I pinged you about this on another PR, but note that this removed the required_ruby_version.

**Comment by kflemin** [comment]
@kbenne I think I'd rather keep it in but bump the version to the new ruby

**Comment by kbenne** [comment]
Very well. Would you be willing to make a commit/PR/merge?

**Comment by kflemin** [comment]
@kbenne: sure! https://github.com/NREL/bcl-gem/pull/30

**Pull request merged**
