### PR TITLE
Schema3

### PR DESCRIPTION
**Pull request by macumber**
@kflemin @asparke2 @nllong these are the proposed changes to make schema version 3 official, what do you think?

### CODE REVIEW

**Comment by macumber** [comment]
I had a few questions about the new outputs section for measures:

* Must short name be a machine name (e.g. no spaces, no capitals, etc) or can it be freeform?  Should there be a restriction on length (e.g. 6 characters)?
* Can outputs have a type?  I assume most are real but can outputs be a string or integer?

**Comment by kflemin** [comment]
@macumber: historically, there haven't been restrictions on short name.  The machine name is covered by the "name" element.

**Comment by nllong** [comment]
agreed with @kflemin, short names can be sentences. They are used on some plots where spacing might be constrained. outputs should be typed.

**Comment by macumber** [comment]
Thanks guys, I think this is good to go now

**Pull request merged**
